name: Build
on:
  workflow_dispatch:
  push:
    branches: [main, ci]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: dotnet build

